apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxtjs
  namespace: architecture-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architecture-review-nuxtjs
  template:
    metadata:
      labels:
        app: architecture-review-nuxtjs
    spec:
      nodeSelector:
        agentpool: user
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: architecture-review-nuxtjs
      containers:
      - name: architecture-review-nuxtjs
        image: aksarchitect.azurecr.io/frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "3000"
        - name: APP_BUILD_SHA
          value: ${APP_BUILD_SHA} # edge case: if git sha is all numbers, this will fail.
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: 0.5
            memory: 512Mi
          requests:
            cpu:  0.25
            memory: 256Mi
