jobs:
- job: Deploy
  displayName: Deploy
  variables:
  - group: mask-subscription-ids
  - group: aks-credentials-kv-group

  steps:
  - template: ../steps/append-sha.yaml
  - template: ../steps/debug-vars.yaml
  - template: ../steps/get-sha.yaml
  # TODO - refactor shared-infra iac to generate key vaults per environment
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - template: ../steps/setup-kubelogin.dev.yaml
  # - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  #   - template: ../steps/setup-kubelogin.staging.yaml

  - bash: |

      # confirm it works
      kubectl get pods --namespace $(appNamespace)

      # now apply
      cat ./manifests/deployment.yaml | envsubst | kubectl apply -f -
      cat ./manifests/service.yaml | envsubst | kubectl apply -f -
      cat ./manifests/ingress.yaml | envsubst | kubectl apply -f -

    displayName: "kubectl apply"
    env:
      KUBECONFIG: $(Build.SourcesDirectory)/.kubeconfig-$(aksClusterName)
      IMAGE_TAG:     $(imageTag)
      APP_BUILD_SHA: $(commitSha)
      INGRESS_HOSTNAME: $(ingressHostname)

  - bash: |
      kubelogin remove-tokens
    displayName: kubelogin - clear cache
