name: 'Continuous Delivery (CD)'

on:
  push:
    branches:
    - main
    - staging
    paths-ignore:
    - '.*'
    - '!.dockerignore'
    - 'CHANGELOG.md'
    - 'README.md'
    - 'infrastructure.*'

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  config:
    needs: ci
    uses: ./.github/workflows/_config.yaml

  output-vars:
    needs: config
    runs-on: ubuntu-latest
    steps:
    - run: echo "Target Environment - ${{ needs.config.outputs.target }}"
    - run: echo "AKS cluster - ${{ needs.config.outputs.cluster }}"
    - run: echo "git sha ${{ needs.config.outputs.git-sha }}"
    - run: echo "Docker tag ${{ needs.config.outputs.docker-tag }}"

  docker:
    needs: config
    uses: ./.github/workflows/_docker.yaml
    with:
      environment:  ${{ needs.config.outputs.target }}
      image-tag:    ${{ needs.config.outputs.docker-tag }}
      git-sha:      ${{ needs.config.outputs.git-sha }}
    secrets:
      AZURE_CLIENT_ID:                  ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID:            ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID:                  ${{ secrets.AZURE_TENANT_ID }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
      AZ_DEFENDER_TOKEN:                ${{ secrets.AZ_DEFENDER_TOKEN }}

  deploy:
    needs: config
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment:    ${{ needs.config.outputs.target }}
      git-sha:        ${{ needs.config.outputs.git-sha }}
      image-tag:      ${{ needs.config.outputs.docker-tag }}
      resource-group: ${{ needs.config.outputs.resource-group }}
      cluster-name:   ${{ needs.config.outputs.cluster }}
      hostname:       ${{ needs.config.outputs.hostname }}
      overlays:       ./manifests/overlays/${{ needs.config.outputs.overlays }}
    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

  e2e:
    needs: [config, docker, deploy]
    uses: ./.github/workflows/_e2e.yaml
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    with:
      url:       ${{ needs.config.outputs.url }}
      build-sha: ${{ needs.config.outputs.git-sha }}
