name: 'Continuous Integration (CI)'

on:
  # Don't check branches b/c CD calls this CI workflow.
  # push:
  #   branches:
  #   - main
  #   - feat/*
  #   - fix/*
  #   paths-ignore:
  #   - 'content/**'
  #   - 'manifests/**'
  #   - 'scss/**'
  #   - 'static/**'
  #   - '**/*.md'
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_call:
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'

    - name: get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm install
      run: npm ci

    - name: audit dependences
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: lint
      run: npm run lint

    - name: unit tests
      run: npm run test

    - name: build
      run: npm run nuxt:build

  docker:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build .
