name: 'Continuous Integration (CI)'

on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
    paths-ignore:
    - 'content/**'
    - 'manifests/**'
    - 'scss/**'
    - 'static/**'
    - '**/*.md'
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm ci

    - name: audit dependences
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: lint
      run: npm run lint

    - name: unit tests
      run: npm run test

    - name: build
      run: npm run nuxt:build

  docker:
    needs: node
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - run: docker build .

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2