name: dev

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    uses: ./.github/workflows/job-docker.yaml
    with:
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
