name: '🧹 Housekeeping - Container Registry'

on:
  schedule:
    - cron: '0 6 * * 1'     # Mondays at 6am
  workflow_dispatch:        # Allow manual runs

permissions:
  id-token: write
  contents: read

env:
  acr-registry: cloudkubereviews
  old-acr-registry: aksarchitect
  dev-naming-pattern: 'frontend:dev-*'
  feature-naming-pattern: 'frontend:feat-*'
  keep-days: 14d
  keep-last: 5

jobs:
  tidy-cloudkubereviews:
    name: 'tidy - cloudkubereviews'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: 'ACR Login'
      run: az acr login --name ${{ env.acr-registry }}

    - name: 'Tidy up - dev images'
      run: |
        RUN_TIDY="acr purge --filter ${{ env.dev-naming-pattern }} --untagged --ago ${{ env.keep-days }} --keep ${{ env.keep-last }}"
        az acr run --cmd "$RUN_TIDY" --registry ${{ env.acr-registry }} /dev/null

    - name: 'Tidy up - feature branch images'
      run: |
        RUN_TIDY="acr purge --filter ${{ env.feature-naming-pattern }} --untagged --ago ${{ env.keep-days }} --keep ${{ env.keep-last }}"
        az acr run --cmd "$RUN_TIDY" --registry ${{ env.acr-registry }} /dev/null


  tidy-aksarchitect:
    name: 'tidy - aksarchitect'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: 'ACR Login'
      run: az acr login --name ${{ env.old-acr-registry }}

    - name: 'Tidy up - dev images'
      run: |
        RUN_TIDY="acr purge --filter ${{ env.dev-naming-pattern }} --untagged --ago ${{ env.keep-days }} --keep ${{ env.keep-last }}"
        az acr run --cmd "$RUN_TIDY" --registry ${{ env.old-acr-registry }} /dev/null


# For details on `acr purge` command, see
# https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge