name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - fix/*
    - feat/*
    - main
    - dev
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: npm ci
    displayName: npm install

  - bash: npm run lint
    displayName: linter

  - bash: npm run test
    displayName: tests